Repository yzharko/spbspu-labs-2024-aads, pull requests merged in 2024-05, with the labels that each got.

#47 zheleznyakov.mark/S1
  zheleznyakov.mark/S1/list.hpp
  zheleznyakov.mark/S1/main.cpp
  zheleznyakov.mark/S1/node.hpp
  zheleznyakov.mark/S1/task.hpp
Labels: .ok, 4/5

#83 doroshenko.anna/S2
  doroshenko.anna/S2/calculationProcess.cpp
  doroshenko.anna/S2/calculationProcess.hpp
  doroshenko.anna/S2/main.cpp
  doroshenko.anna/S2/queue.hpp
  doroshenko.anna/S2/stack.hpp
  doroshenko.anna/common/list.hpp
Labels: .ok, 3/5

#91 reznikova.anna/S1
  reznikova.anna/S1/ConstIterator.hpp
  reznikova.anna/S1/Iterator.hpp
  reznikova.anna/S1/List.hpp
  reznikova.anna/S1/ListProcess.cpp
  reznikova.anna/S1/ListProcess.hpp
  reznikova.anna/S1/Node.hpp
  reznikova.anna/S1/main.cpp
Labels: .ok, 4/5

#79 taskaev.matvei/S2
  taskaev.matvei/S2/IdentifierMath.cpp
  taskaev.matvei/S2/IdentifierMath.hpp
  taskaev.matvei/S2/Queue.hpp
  taskaev.matvei/S2/Stack.hpp
  taskaev.matvei/S2/function.cpp
  taskaev.matvei/S2/function.hpp
  taskaev.matvei/S2/main.cpp
  taskaev.matvei/common/List.hpp
Labels: .ok, 4/5

#85 miheev.egor/S2
  miheev.egor/S2/expressionElement.cpp
  miheev.egor/S2/expressionElement.hpp
  miheev.egor/S2/inputProcessing.cpp
  miheev.egor/S2/inputProcessing.hpp
  miheev.egor/S2/main.cpp
  miheev.egor/S2/operands.cpp
  miheev.egor/S2/operands.hpp
  miheev.egor/S2/operations.cpp
  miheev.egor/S2/operations.hpp
  miheev.egor/S2/postfixElement.cpp
  miheev.egor/S2/postfixElement.hpp
  miheev.egor/S2/queue.hpp
  miheev.egor/S2/stack.hpp
  miheev.egor/common/list.hpp
Labels: .ok, 5/5

#45 zhitnyj.dmytriy/S1
  zhitnyj.dmitriy/S1/List.hpp
  zhitnyj.dmitriy/S1/SequenceHandler.cpp
  zhitnyj.dmitriy/S1/SequenceHandler.hpp
  zhitnyj.dmitriy/S1/main.cpp
Labels: .ok, 4/5

#63 ponomarev.viacheslav/S1
  ponomarev.viacheslav/S1/cutFunctions.cpp
  ponomarev.viacheslav/S1/cutFunctions.hpp
  ponomarev.viacheslav/S1/list.hpp
  ponomarev.viacheslav/S1/main.cpp
  ponomarev.viacheslav/S1/outputFunctions.hpp
Labels: .ok, 3/5, .debuff

#81 redko.arina/S4
  redko.arina/S4/binarySearchTree.hpp
  redko.arina/S4/dataFunctions.cpp
  redko.arina/S4/dataFunctions.hpp
  redko.arina/S4/main.cpp
Labels: .ok, 5/5, .chosenOne

#82 khoroshkin.maksim/S4
  khoroshkin.maksim/S4/commands.cpp
  khoroshkin.maksim/S4/commands.hpp
  khoroshkin.maksim/S4/main.cpp
  khoroshkin.maksim/S4/tree.hpp
Labels: 5/5, .chosenOne

#60 mihalchenko.vladislav/S1
  mihalchenko.vladislav/S1/InpOutpProcessing.cpp
  mihalchenko.vladislav/S1/InpOutpProcessing.hpp
  mihalchenko.vladislav/S1/list.hpp
  mihalchenko.vladislav/S1/main.cpp
Labels: .ok, 5/5

#67 jirkov.vladimir/S1
  jirkov.vladimir/S1/calculatingData.cpp
  jirkov.vladimir/S1/calculatingData.hpp
  jirkov.vladimir/S1/list.hpp
  jirkov.vladimir/S1/main.cpp
  jirkov.vladimir/S1/node.hpp
Labels: .ok, 4/5

#64 lisitsyna.yulia/S1
  lisitsyna.yulia/S1/except_sum.cpp
  lisitsyna.yulia/S1/except_sum.hpp
  lisitsyna.yulia/S1/list.hpp
  lisitsyna.yulia/S1/main.cpp
  lisitsyna.yulia/S1/sequences_funcs.cpp
  lisitsyna.yulia/S1/sequences_funcs.hpp
Labels: .ok, 3/5

#93 redko.arina/S5
  redko.arina/S5/main.cpp
  redko.arina/S5/sumAndOrder.hpp
  redko.arina/common/binarySearchTree.hpp
  redko.arina/common/dataFunctions.cpp
  redko.arina/common/dataFunctions.hpp
  redko.arina/common/queue.hpp
  redko.arina/common/stack.hpp
Labels: .ok, 5/5

#84 sobolevsky.misha/S2
  sobolevsky.misha/S1/main.cpp
  sobolevsky.misha/S2/functions.cpp
  sobolevsky.misha/S2/functions.hpp
  sobolevsky.misha/S2/main.cpp
  sobolevsky.misha/S2/queue.hpp
  sobolevsky.misha/S2/stack.hpp
  sobolevsky.misha/common/iterator.hpp
  sobolevsky.misha/common/list.hpp
  sobolevsky.misha/common/node.hpp
Labels: .ok, 2/5

#92 khoroshkin.maksim/S5
  khoroshkin.maksim/S5/functionalObject.hpp
  khoroshkin.maksim/S5/main.cpp
  khoroshkin.maksim/S5/traverseFuncs.cpp
  khoroshkin.maksim/S5/traverseFuncs.hpp
  khoroshkin.maksim/common/commands.cpp
  khoroshkin.maksim/common/commands.hpp
  khoroshkin.maksim/common/list.hpp
  khoroshkin.maksim/common/queue.hpp
  khoroshkin.maksim/common/stack.hpp
  khoroshkin.maksim/common/tree.hpp
Labels: .ok, 5/5

#86 zheleznyakov.mark/S2
  zheleznyakov.mark/S2/input.cpp
  zheleznyakov.mark/S2/input.hpp
  zheleznyakov.mark/S2/main.cpp
  zheleznyakov.mark/S2/math.cpp
  zheleznyakov.mark/S2/math.hpp
  zheleznyakov.mark/S2/queue.hpp
  zheleznyakov.mark/S2/stack.hpp
  zheleznyakov.mark/common/list.hpp
  zheleznyakov.mark/common/node.hpp
Labels: .ok, 3/5

#94 psarev.alexandr/S2
  psarev.alexandr/S2/main.cpp
  psarev.alexandr/S2/queue.hpp
  psarev.alexandr/S2/stack.hpp
  psarev.alexandr/S2/termFuncs.cpp
  psarev.alexandr/S2/termFuncs.hpp
  psarev.alexandr/common/list.hpp
Labels: .ok, 3/5

#87 kovshikov.nikita/S2
  kovshikov.nikita/S2/computing.cpp
  kovshikov.nikita/S2/computing.hpp
  kovshikov.nikita/S2/main.cpp
  kovshikov.nikita/S2/queue.hpp
  kovshikov.nikita/S2/stack.hpp
  kovshikov.nikita/S2/text.txt
  kovshikov.nikita/common/doublelist.hpp
  kovshikov.nikita/common/node.hpp
Labels: .ok, 3/5

#53 litsinger.ernest/S1
  litsinger.ernest/S1/func.hpp
  litsinger.ernest/S1/list.hpp
  litsinger.ernest/S1/main.cpp
Labels: .ok, 3/5

#88 anikanov.vladislav/S2
  anikanov.vladislav/S1/mainExtensions.hpp
  anikanov.vladislav/S2/bracket.cpp
  anikanov.vladislav/S2/bracket.hpp
  anikanov.vladislav/S2/elementOfExpression.hpp
  anikanov.vladislav/S2/main.cpp
  anikanov.vladislav/S2/mainExtension.cpp
  anikanov.vladislav/S2/mainExtension.hpp
  anikanov.vladislav/S2/operand.cpp
  anikanov.vladislav/S2/operand.hpp
  anikanov.vladislav/S2/operation.cpp
  anikanov.vladislav/S2/operation.hpp
  anikanov.vladislav/S2/queue.hpp
  anikanov.vladislav/S2/stack.hpp
  anikanov.vladislav/common/list.hpp
Labels: .ok, 4/5

#89 nikiforov.alexander/S2
  nikiforov.alexander/S2/dataTypes.cpp
  nikiforov.alexander/S2/dataTypes.hpp
  nikiforov.alexander/S2/functions.cpp
  nikiforov.alexander/S2/functions.hpp
  nikiforov.alexander/S2/main.cpp
  nikiforov.alexander/S2/queue.hpp
  nikiforov.alexander/S2/stack.hpp
  nikiforov.alexander/common/list.hpp
Labels: .ok, 4/5

#62 hohlova.polina/S1
  hohlova.polina/S1/list.hpp
  hohlova.polina/S1/main.cpp
  hohlova.polina/S1/parseNums.cpp
  hohlova.polina/S1/parseNums.hpp
Labels: .ok, 2/5, .debuff

#95 zhitnyj.dmytriy/S2
  zhitnyj.dmitriy/S1/SequenceHandler.hpp
  zhitnyj.dmitriy/S2/ExpressionEvaluator.cpp
  zhitnyj.dmitriy/S2/ExpressionEvaluator.hpp
  zhitnyj.dmitriy/S2/ExpressionItem.hpp
  zhitnyj.dmitriy/S2/Operand.cpp
  zhitnyj.dmitriy/S2/Operand.hpp
  zhitnyj.dmitriy/S2/Operator.cpp
  zhitnyj.dmitriy/S2/Operator.hpp
  zhitnyj.dmitriy/S2/Queue.hpp
  zhitnyj.dmitriy/S2/Stack.hpp
  zhitnyj.dmitriy/S2/main.cpp
  zhitnyj.dmitriy/common/List.hpp
Labels: .ok, 4/5

#52 panov.ilya/S1
  panov.ilya/S1/list.hpp
  panov.ilya/S1/main.cpp
Labels: .ok, 2/5, .derSchwarzePunkt, .debuff

#101 miheev.egor/S4
  miheev.egor/S4/IOProcessing.cpp
  miheev.egor/S4/IOProcessing.hpp
  miheev.egor/S4/commands.cpp
  miheev.egor/S4/commands.hpp
  miheev.egor/S4/main.cpp
  miheev.egor/S4/tree.hpp
Labels: .ok, 4/5

#100 khoroshkin.maksim/S6
  khoroshkin.maksim/S6/inputProcessing.hpp
  khoroshkin.maksim/S6/main.cpp
  khoroshkin.maksim/S6/sort.hpp
  khoroshkin.maksim/common/list.hpp
Labels: .ok

#66 gorbunova.alena/S1
  gorbunova.alena/S1/func.hpp
  gorbunova.alena/S1/list.hpp
  gorbunova.alena/S1/main.cpp
Labels: .ok, 2/5, .debuff

#99 redko.arina/S6
  redko.arina/S6/bucketSort.hpp
  redko.arina/S6/main.cpp
  redko.arina/S6/outputFunction.hpp
  redko.arina/S6/quickSort.hpp
Labels: .ok

#98 mihalchenko.vladislav/S2
  mihalchenko.vladislav/S2/main.cpp
  mihalchenko.vladislav/S2/processing.cpp
  mihalchenko.vladislav/S2/processing.hpp
  mihalchenko.vladislav/S2/queue.hpp
  mihalchenko.vladislav/S2/stack.hpp
  mihalchenko.vladislav/S2/types.cpp
  mihalchenko.vladislav/S2/types.hpp
  mihalchenko.vladislav/common/list.hpp
Labels: .ok, 4/5

#102 ponomarev.viacheslav/S2
  ponomarev.viacheslav/S2/computationalFunctions.cpp
  ponomarev.viacheslav/S2/computationalFunctions.hpp
  ponomarev.viacheslav/S2/inputFunctions.cpp
  ponomarev.viacheslav/S2/inputFunctions.hpp
  ponomarev.viacheslav/S2/main.cpp
  ponomarev.viacheslav/S2/queue.hpp
  ponomarev.viacheslav/S2/stack.hpp
  ponomarev.viacheslav/S2/typing.cpp
  ponomarev.viacheslav/S2/typing.hpp
  ponomarev.viacheslav/common/cutFunctions.cpp
  ponomarev.viacheslav/common/cutFunctions.hpp
  ponomarev.viacheslav/common/list.hpp
Labels: .ok, 5/5

#104 zhitnyj.dmytriy/S4
  zhitnyj.dmitriy/S4/BinarySearchTree.hpp
  zhitnyj.dmitriy/S4/CommandProcessor.cpp
  zhitnyj.dmitriy/S4/CommandProcessor.hpp
  zhitnyj.dmitriy/S4/main.cpp
Labels: .ok, 4/5

#103 hohlova.polina/s2
  hohlova.polina/S2/ExpressionCalc.cpp
  hohlova.polina/S2/ExpressionCalc.hpp
  hohlova.polina/S2/main.cpp
  hohlova.polina/S2/queue.hpp
  hohlova.polina/S2/stack.hpp
  hohlova.polina/common/list.hpp
Labels: .ok, 3/5

#90 doroshenko.anna/S4
  doroshenko.anna/S4/BinarySearchTree.hpp
  doroshenko.anna/S4/main.cpp
  doroshenko.anna/S4/treeProcess.cpp
  doroshenko.anna/S4/treeProcess.hpp
Labels: .ok, 4/5

#108 sobolevsky.misha/S4
  sobolevsky.misha/S4/commands.cpp
  sobolevsky.misha/S4/commands.hpp
  sobolevsky.misha/S4/main.cpp
  sobolevsky.misha/S4/tree.hpp
  sobolevsky.misha/S4/utils.cpp
  sobolevsky.misha/S4/utils.hpp
Labels: .ok, 4/5

#114 zheleznyakov.mark/S4
  zheleznyakov.mark/S4/commands.cpp
  zheleznyakov.mark/S4/commands.hpp
  zheleznyakov.mark/S4/datatypes.hpp
  zheleznyakov.mark/S4/input.cpp
  zheleznyakov.mark/S4/input.hpp
  zheleznyakov.mark/S4/main.cpp
  zheleznyakov.mark/S4/tree.hpp
Labels: .ok, 4/5

#109 miheev.egor/S5
  miheev.egor/S5/IOFunctions.cpp
  miheev.egor/S5/IOFunctions.hpp
  miheev.egor/S5/keySumm.cpp
  miheev.egor/S5/keySumm.hpp
  miheev.egor/S5/main.cpp
  miheev.egor/common/queue.hpp
  miheev.egor/common/stack.hpp
  miheev.egor/common/tree.hpp
Labels: .ok, 5/5

#107 kovshikov.nikita/S4
  kovshikov.nikita/S4/BinarySearchTree.hpp
  kovshikov.nikita/S4/main.cpp
  kovshikov.nikita/S4/treeProcess.cpp
  kovshikov.nikita/S4/treeProcess.hpp
Labels: .ok, 4/5
