Repository yzharko/spbspu-labs-2024-aads, pull requests merged in 2024-06, with the labels that each got.

#115 redko.arina/F0
  redko.arina/F0/HuffmanCode.cpp
  redko.arina/F0/HuffmanCode.hpp
  redko.arina/F0/delimiter.cpp
  redko.arina/F0/delimiter.hpp
  redko.arina/F0/main.cpp
  redko.arina/F0/messageFunctions.cpp
  redko.arina/F0/messageFunctions.hpp
  redko.arina/F0/userCommands.cpp
  redko.arina/F0/userCommands.hpp
Labels: .ok, 5/5

#112 sobolevsky.misha/S5
  sobolevsky.misha/S4/tree.hpp
  sobolevsky.misha/S5/commands.cpp
  sobolevsky.misha/S5/commands.hpp
  sobolevsky.misha/S5/errorsANDinput.cpp
  sobolevsky.misha/S5/errorsANDinput.hpp
  sobolevsky.misha/S5/keySumm.cpp
  sobolevsky.misha/S5/keySumm.hpp
  sobolevsky.misha/S5/main.cpp
  sobolevsky.misha/common/list.hpp
  sobolevsky.misha/common/queue.hpp
  sobolevsky.misha/common/stack.hpp
  sobolevsky.misha/common/tree.hpp
Labels: .ok, 5/5

#116 kovshikov.nikita/S5
  kovshikov.nikita/S5/TreeTraversal.hpp
  kovshikov.nikita/S5/main.cpp
  kovshikov.nikita/S5/process.cpp
  kovshikov.nikita/S5/process.hpp
  kovshikov.nikita/common/BinarySearchTree.hpp
  kovshikov.nikita/common/queue.hpp
  kovshikov.nikita/common/stack.hpp
Labels: .ok, 3/5

#117 doroshenko.anna/S5
  doroshenko.anna/S5/KeyValSumm.cpp
  doroshenko.anna/S5/KeyValSumm.hpp
  doroshenko.anna/S5/commands.cpp
  doroshenko.anna/S5/commands.hpp
  doroshenko.anna/S5/main.cpp
  doroshenko.anna/common/BinarySearchTree.hpp
  doroshenko.anna/common/queue.hpp
  doroshenko.anna/common/stack.hpp
Labels: .ok, 3/5

#122 miheev.egor/S6
  miheev.egor/S6/IOProcessing.hpp
  miheev.egor/S6/main.cpp
  miheev.egor/S6/messages.cpp
  miheev.egor/S6/messages.hpp
  miheev.egor/S6/sorts.hpp
  miheev.egor/common/list.hpp
Labels: .ok

#121 khoroshkin.maksim/F0
  khoroshkin.maksim/F0/commands.cpp
  khoroshkin.maksim/F0/commands.hpp
  khoroshkin.maksim/F0/datastruct.cpp
  khoroshkin.maksim/F0/datastruct.hpp
  khoroshkin.maksim/F0/delimiter.hpp
  khoroshkin.maksim/F0/graph.hpp
  khoroshkin.maksim/F0/main.cpp
  khoroshkin.maksim/F0/scopeguard.cpp
  khoroshkin.maksim/F0/scopeguard.hpp
  khoroshkin.maksim/common/list.hpp
Labels: .ok, 5/5

#106 zhitnyj.dmytriy/S5
  zhitnyj.dmitriy/S1/SequenceHandler.cpp
  zhitnyj.dmitriy/S1/SequenceHandler.hpp
  zhitnyj.dmitriy/S1/main.cpp
  zhitnyj.dmitriy/S2/ExpressionEvaluator.cpp
  zhitnyj.dmitriy/S2/ExpressionEvaluator.hpp
  zhitnyj.dmitriy/S2/ExpressionItem.hpp
  zhitnyj.dmitriy/S2/Operand.cpp
  zhitnyj.dmitriy/S2/Operand.hpp
  zhitnyj.dmitriy/S2/Operator.cpp
  zhitnyj.dmitriy/S2/Operator.hpp
  zhitnyj.dmitriy/S2/Queue.hpp
  zhitnyj.dmitriy/S2/Stack.hpp
  zhitnyj.dmitriy/S2/main.cpp
  zhitnyj.dmitriy/S4/BinarySearchTree.hpp
  zhitnyj.dmitriy/S4/CommandProcessor.cpp
  zhitnyj.dmitriy/S4/CommandProcessor.hpp
  zhitnyj.dmitriy/S4/main.cpp
  zhitnyj.dmitriy/S5/KeySum.hpp
  zhitnyj.dmitriy/S5/TreeTraversal.cpp
  zhitnyj.dmitriy/S5/TreeTraversal.hpp
  zhitnyj.dmitriy/S5/main.cpp
  zhitnyj.dmitriy/common/BinarySearchTree.hpp
  zhitnyj.dmitriy/common/List.hpp
  zhitnyj.dmitriy/common/Queue.hpp
  zhitnyj.dmitriy/common/Stack.hpp
Labels: .ok, 5/5

#105 psarev.alexandr/S4
  psarev.alexandr/S4/avlTree.hpp
  psarev.alexandr/S4/execCommands.cpp
  psarev.alexandr/S4/execCommands.hpp
  psarev.alexandr/S4/main.cpp
Labels: .ok, 5/5

#118 sukacheva.maria/S4
  sukacheva.maria/S4/BST.hpp
  sukacheva.maria/S4/Commands.cpp
  sukacheva.maria/S4/Commands.hpp
  sukacheva.maria/S4/ErrorMessage.cpp
  sukacheva.maria/S4/ErrorMessage.hpp
  sukacheva.maria/S4/Node.hpp
  sukacheva.maria/S4/main.cpp
Labels: .ok, 4/5

#120 ponomarev.viacheslav/S4
  ponomarev.viacheslav/S4/IOFunctions.cpp
  ponomarev.viacheslav/S4/IOFunctions.hpp
  ponomarev.viacheslav/S4/binarySearchTreeAVL.hpp
  ponomarev.viacheslav/S4/commands.cpp
  ponomarev.viacheslav/S4/commands.hpp
  ponomarev.viacheslav/S4/main.cpp
Labels: .ok, 4/5

#128 sobolevsky.misha/S6
  sobolevsky.misha/S6/main.cpp
  sobolevsky.misha/S6/mergeSort.hpp
  sobolevsky.misha/S6/shakerSort.hpp
  sobolevsky.misha/S6/sortsAgregatorContainerIOandErrors.hpp
Labels: .ok

#127 nikiforov.alexander/S4
  nikiforov.alexander/S4/AvlTree.hpp
  nikiforov.alexander/S4/commands.cpp
  nikiforov.alexander/S4/commands.hpp
  nikiforov.alexander/S4/main.cpp
Labels: .ok, 5/5

#129 psarev.alexandr/S5
  psarev.alexandr/S5/main.cpp
  psarev.alexandr/S5/taskSumm.cpp
  psarev.alexandr/S5/taskSumm.hpp
  psarev.alexandr/S5/traverseCmds.cpp
  psarev.alexandr/S5/traverseCmds.hpp
  psarev.alexandr/common/avlTree.hpp
  psarev.alexandr/common/queue.hpp
  psarev.alexandr/common/stack.hpp
Labels: .ok, 5/5

#119 kovshikov.nikita/S6
  kovshikov.nikita/S6/main.cpp
  kovshikov.nikita/S6/random.hpp
  kovshikov.nikita/S6/sort.hpp
  kovshikov.nikita/common/doublelist.hpp
Labels: .ok

#133 nikiforov.alexander/S5
  nikiforov.alexander/S2/functions.cpp
  nikiforov.alexander/S2/functions.hpp
  nikiforov.alexander/S5/commandsTraverse.cpp
  nikiforov.alexander/S5/commandsTraverse.hpp
  nikiforov.alexander/S5/main.cpp
  nikiforov.alexander/S5/structSumm.hpp
  nikiforov.alexander/common/AvlTree.hpp
  nikiforov.alexander/common/commands.cpp
  nikiforov.alexander/common/commands.hpp
  nikiforov.alexander/common/queue.hpp
  nikiforov.alexander/common/stack.hpp
Labels: .ok, 5/5

#134 ponomarev.viacheslav/S5
  ponomarev.viacheslav/S5/commands.cpp
  ponomarev.viacheslav/S5/commands.hpp
  ponomarev.viacheslav/S5/funcObj.cpp
  ponomarev.viacheslav/S5/funcObj.hpp
  ponomarev.viacheslav/S5/main.cpp
  ponomarev.viacheslav/common/IOFunctions.cpp
  ponomarev.viacheslav/common/IOFunctions.hpp
  ponomarev.viacheslav/common/binarySearchTreeAVL.hpp
  ponomarev.viacheslav/common/queue.hpp
  ponomarev.viacheslav/common/stack.hpp
Labels: .ok, 5/5

#126 anikanov.vladislav/S4
  anikanov.vladislav/S4/binarySearchTree.hpp
  anikanov.vladislav/S4/main.cpp
  anikanov.vladislav/S4/mainExtansion.cpp
  anikanov.vladislav/S4/mainExtansion.hpp
Labels: .ok, 4/5

#132 zhitnyj.dmytriy/S6
  zhitnyj.dmitriy/S6/main.cpp
  zhitnyj.dmitriy/S6/random.hpp
  zhitnyj.dmitriy/S6/sortOperations.hpp
Labels: .ok

#139 psarev.alexandr/S6
  psarev.alexandr/S6/main.cpp
  psarev.alexandr/S6/qSort.hpp
  psarev.alexandr/S6/shellSort.hpp
  psarev.alexandr/S6/sortFuncs.hpp
  psarev.alexandr/S6/utils.cpp
  psarev.alexandr/S6/utils.hpp
  psarev.alexandr/common/list.hpp
Labels: .ok

#138 reznikova.anna/S4
  reznikova.anna/S4/Commands.cpp
  reznikova.anna/S4/Commands.hpp
  reznikova.anna/S4/Tree.hpp
  reznikova.anna/S4/main.cpp
Labels: .ok, 5/5

#140 doroshenko.anna/S6
  doroshenko.anna/S6/main.cpp
  doroshenko.anna/S6/sort.hpp
  doroshenko.anna/common/list.hpp
Labels: .ok

#124 taskaev.matvei/S4
  taskaev.matvei/S4/BSTree.hpp
  taskaev.matvei/S4/functions.cpp
  taskaev.matvei/S4/functions.hpp
  taskaev.matvei/S4/main.cpp
Labels: 3/5

#125 mihalchenko.vladislav/S4
  mihalchenko.vladislav/S4/AVLtree.hpp
  mihalchenko.vladislav/S4/commands.cpp
  mihalchenko.vladislav/S4/commands.hpp
  mihalchenko.vladislav/S4/main.cpp
Labels: .ok, 3/5

#130 sukacheva.maria/S5
  sukacheva.maria/S4/Node.hpp
  sukacheva.maria/S5/DataProcessing.cpp
  sukacheva.maria/S5/DataProcessing.hpp
  sukacheva.maria/S5/KeySum.hpp
  sukacheva.maria/S5/main.cpp
  sukacheva.maria/common/BST.hpp
  sukacheva.maria/common/ErrorMessage.cpp
  sukacheva.maria/common/ErrorMessage.hpp
  sukacheva.maria/common/Queue.hpp
  sukacheva.maria/common/Stack.hpp
  sukacheva.maria/common/TreeNode.hpp
Labels: .ok, 3/5

#142 anikanov.vladislav/S5
  anikanov.vladislav/S2/main.cpp
  anikanov.vladislav/S2/mainExtension.cpp
  anikanov.vladislav/S2/mainExtension.hpp
  anikanov.vladislav/S4/main.cpp
  anikanov.vladislav/S4/mainExtansion.cpp
  anikanov.vladislav/S4/mainExtansion.hpp
  anikanov.vladislav/S5/main.cpp
  anikanov.vladislav/S5/mainExtansion.cpp
  anikanov.vladislav/S5/mainExtansion.hpp
  anikanov.vladislav/S5/resultCounter.cpp
  anikanov.vladislav/S5/resultCounter.hpp
  anikanov.vladislav/common/binarySearchTree.hpp
  anikanov.vladislav/common/list.hpp
  anikanov.vladislav/common/queue.hpp
  anikanov.vladislav/common/stack.hpp
Labels: .ok, 3/5

#141 ponomarev.viacheslav/S6
  ponomarev.viacheslav/S6/distributionFunctions.hpp
  ponomarev.viacheslav/S6/main.cpp
  ponomarev.viacheslav/S6/outputErrorFunctions.cpp
  ponomarev.viacheslav/S6/outputErrorFunctions.hpp
  ponomarev.viacheslav/S6/sorts.hpp
Labels: .ok

#144 nikiforov.alexander/S6
  nikiforov.alexander/S6/funcsSort.hpp
  nikiforov.alexander/S6/main.cpp
  nikiforov.alexander/S6/mergeSort.hpp
  nikiforov.alexander/S6/shakerSort.hpp
Labels: .ok

#145 psarev.alexandr/F0
  psarev.alexandr/F0/internalFuncs.cpp
  psarev.alexandr/F0/internalFuncs.hpp
  psarev.alexandr/F0/main.cpp
  psarev.alexandr/F0/userCmds.cpp
  psarev.alexandr/F0/userCmds.hpp
  psarev.alexandr/common/avlTree.hpp
  psarev.alexandr/common/list.hpp
Labels: .ok, 5/5

#146 doroshenko.anna/F0
  doroshenko.anna/F0/commands.cpp
  doroshenko.anna/F0/commands.hpp
  doroshenko.anna/F0/main.cpp
  doroshenko.anna/common/BinarySearchTree.hpp
Labels: .ok, 5/5

#131 miheev.egor/F0
  miheev.egor/F0/IOFunctions.cpp
  miheev.egor/F0/IOFunctions.hpp
  miheev.egor/F0/commands.cpp
  miheev.egor/F0/commands.hpp
  miheev.egor/F0/graph.cpp
  miheev.egor/F0/graph.hpp
  miheev.egor/F0/main.cpp
  miheev.egor/F0/messages.cpp
  miheev.egor/F0/messages.hpp
  miheev.egor/F0/workspace.hpp
  miheev.egor/common/delimiters.cpp
  miheev.egor/common/delimiters.hpp
  miheev.egor/common/list.hpp
  miheev.egor/common/scopeguard.cpp
  miheev.egor/common/scopeguard.hpp
  miheev.egor/common/tree.hpp
Labels: .ok, 5/5

#149 nikiforov.alexander/F0
  nikiforov.alexander/F0/dictionaryCommands.cpp
  nikiforov.alexander/F0/dictionaryCommands.hpp
  nikiforov.alexander/F0/main.cpp
Labels: .ok, 5/5

#147 taskaev.matvei/S5
  taskaev.matvei/S5/functions.cpp
  taskaev.matvei/S5/functions.hpp
  taskaev.matvei/S5/main.cpp
  taskaev.matvei/common/BSTree.hpp
  taskaev.matvei/common/Queue.hpp
  taskaev.matvei/common/Stack.hpp
Labels: .ok, 3/5

#137 kovshikov.nikita/F0
  kovshikov.nikita/F0/createGraph.cpp
  kovshikov.nikita/F0/createGraph.hpp
  kovshikov.nikita/F0/main.cpp
  kovshikov.nikita/F0/orientedGraph.cpp
  kovshikov.nikita/F0/orientedGraph.hpp
  kovshikov.nikita/F0/outMessage.cpp
  kovshikov.nikita/F0/outMessage.hpp
  kovshikov.nikita/F0/workingGraph.cpp
  kovshikov.nikita/F0/workingGraph.hpp
  kovshikov.nikita/common/BinarySearchTree.hpp
  kovshikov.nikita/common/doublelist.hpp
  kovshikov.nikita/common/random.hpp
  kovshikov.nikita/common/sort.hpp
Labels: .ok, 5/5

#152 sukacheva.maria/S6
  sukacheva.maria/S6/DataProcessing.hpp
  sukacheva.maria/S6/main.cpp
  sukacheva.maria/S6/sorts.hpp
Labels: .ok

#150 anikanov.vladislav/S6
  anikanov.vladislav/S6/main.cpp
  anikanov.vladislav/S6/mainExtension.cpp
  anikanov.vladislav/S6/mainExtension.hpp
Labels: .ok

#151 ponomarev.viacheslav/F0
  ponomarev.viacheslav/F0/accessoryFunctions.cpp
  ponomarev.viacheslav/F0/accessoryFunctions.hpp
  ponomarev.viacheslav/F0/codingHuffman.cpp
  ponomarev.viacheslav/F0/codingHuffman.hpp
  ponomarev.viacheslav/F0/commands.cpp
  ponomarev.viacheslav/F0/commands.hpp
  ponomarev.viacheslav/F0/main.cpp
  ponomarev.viacheslav/common/list.hpp
Labels: .ok, 5/5

#154 zhitnyj.dmytriy/F0
  zhitnyj.dmitriy/F0/Commands.cpp
  zhitnyj.dmitriy/F0/Commands.hpp
  zhitnyj.dmitriy/F0/Graph.hpp
  zhitnyj.dmitriy/F0/GraphUtils.cpp
  zhitnyj.dmitriy/F0/GraphUtils.hpp
  zhitnyj.dmitriy/F0/main.cpp
Labels: .ok, 4/5

#148 zheleznyakov.mark/F0
  zheleznyakov.mark/F0/commands.cpp
  zheleznyakov.mark/F0/commands.hpp
  zheleznyakov.mark/F0/dict.cpp
  zheleznyakov.mark/F0/dict.hpp
  zheleznyakov.mark/F0/main.cpp
  zheleznyakov.mark/common/list.hpp
  zheleznyakov.mark/common/tree.hpp
Labels: .ok, 5/5

#156 sobolevsky.misha/F0
  sobolevsky.misha/F0/commands.cpp
  sobolevsky.misha/F0/commands.hpp
  sobolevsky.misha/F0/main.cpp
  sobolevsky.misha/F0/myList.hpp
  sobolevsky.misha/F0/myMap.hpp
  sobolevsky.misha/F0/myMultiMap.hpp
  sobolevsky.misha/F0/utilsForDictsAndErrors.cpp
  sobolevsky.misha/F0/utilsForDictsAndErrors.hpp
Labels: .ok, 4/5

#160 aniknaov.vladislav/F0
  anikanov.vladislav/F0/changeMenuScene.cpp
  anikanov.vladislav/F0/changeMenuScene.hpp
  anikanov.vladislav/F0/graphMenuScene.cpp
  anikanov.vladislav/F0/graphMenuScene.hpp
  anikanov.vladislav/F0/main.cpp
  anikanov.vladislav/F0/mainMenuScene.cpp
  anikanov.vladislav/F0/mainMenuScene.hpp
  anikanov.vladislav/F0/myAlgorithms.cpp
  anikanov.vladislav/F0/myAlgorithms.hpp
  anikanov.vladislav/F0/runMatrixScene.cpp
  anikanov.vladislav/F0/runMatrixScene.hpp
  anikanov.vladislav/F0/scene.cpp
  anikanov.vladislav/F0/scene.hpp
  anikanov.vladislav/F0/sceneManager.cpp
  anikanov.vladislav/F0/sceneManager.hpp
  anikanov.vladislav/F0/settings.cpp
  anikanov.vladislav/F0/settings.hpp
  anikanov.vladislav/common/list.hpp
Labels: .ok, 4/5

#153 reznikova.anna/S6
  reznikova.anna/S6/InputProcessing.hpp
  reznikova.anna/S6/Sort.hpp
  reznikova.anna/S6/main.cpp
  reznikova.anna/common/Iterator.hpp
Labels: .ok

#161 mihalchenko.vladislav/S5
  mihalchenko.vladislav/S5/commands.cpp
  mihalchenko.vladislav/S5/commands.hpp
  mihalchenko.vladislav/S5/main.cpp
  mihalchenko.vladislav/common/AVLtree.hpp
  mihalchenko.vladislav/common/list.hpp
  mihalchenko.vladislav/common/queue.hpp
  mihalchenko.vladislav/common/stack.hpp
Labels: .ok, 3/5

#157 sukacheva.maria/F0
  sukacheva.maria/F0/ActualGraph.cpp
  sukacheva.maria/F0/ActualGraph.hpp
  sukacheva.maria/F0/commands.cpp
  sukacheva.maria/F0/commands.hpp
  sukacheva.maria/F0/graph.cpp
  sukacheva.maria/F0/graph.hpp
  sukacheva.maria/F0/main.cpp
  sukacheva.maria/common/BST.hpp
  sukacheva.maria/common/List.hpp
Labels: .ok, 4/5

#155 taskaev.matvei/S6
  taskaev.matvei/S6/main.cpp
  taskaev.matvei/S6/sortFunctions.hpp
  taskaev.matvei/S6/workSort.hpp
  taskaev.matvei/common/List.hpp
Labels: .ok

#162 mihalchenko.vladislav/S6
  mihalchenko.vladislav/S6/IOprocessing.hpp
  mihalchenko.vladislav/S6/details.cpp
  mihalchenko.vladislav/S6/details.hpp
  mihalchenko.vladislav/S6/main.cpp
  mihalchenko.vladislav/S6/sorts.hpp
  mihalchenko.vladislav/common/AVLtree.hpp
  mihalchenko.vladislav/common/list.hpp
Labels: .ok

#158 mihalchenko.vladislav/F0
  mihalchenko.vladislav/F0/commands.cpp
  mihalchenko.vladislav/F0/commands.hpp
  mihalchenko.vladislav/F0/details.hpp
  mihalchenko.vladislav/F0/helpDelimiters.cpp
  mihalchenko.vladislav/F0/helpDelimiters.hpp
  mihalchenko.vladislav/F0/helpFunctions.cpp
  mihalchenko.vladislav/F0/helpFunctions.hpp
  mihalchenko.vladislav/F0/main.cpp
Labels: .ok, 5/5

#163 reznikova.anna/F0
  reznikova.anna/F0/Commands.cpp
  reznikova.anna/F0/Commands.hpp
  reznikova.anna/F0/Graph.cpp
  reznikova.anna/F0/Graph.hpp
  reznikova.anna/F0/Vertex.cpp
  reznikova.anna/F0/Vertex.hpp
  reznikova.anna/F0/WorkSpace.cpp
  reznikova.anna/F0/WorkSpace.hpp
  reznikova.anna/F0/main.cpp
  reznikova.anna/common/Iterator.hpp
  reznikova.anna/common/List.hpp
Labels: .ok, 4/5

#159 taskaev.matvei/F0
  taskaev.matvei/F0/Command.cpp
  taskaev.matvei/F0/Command.hpp
  taskaev.matvei/F0/HuffmanTree.cpp
  taskaev.matvei/F0/HuffmanTree.hpp
  taskaev.matvei/F0/main.cpp
  taskaev.matvei/common/BSTree.hpp
Labels: .ok, 3/5

#110 hohlova.polina/S4
  hohlova.polina/S4/WorkerBST.cpp
  hohlova.polina/S4/WorkerBST.hpp
  hohlova.polina/S4/main.cpp
  hohlova.polina/common/BinarySearchTree.hpp
  hohlova.polina/common/queue.hpp
  hohlova.polina/common/stack.hpp
Labels: .ok, 3/5

#111 zasulsky.egor/S2
  zasulsky.egor/S2/Queue.hpp
  zasulsky.egor/S2/Stack.hpp
  zasulsky.egor/S2/functions.cpp
  zasulsky.egor/S2/functions.hpp
  zasulsky.egor/S2/main.cpp
  zasulsky.egor/common/ForwardList.hpp
  zasulsky.egor/common/Node.hpp
  zasulsky.egor/common/parser.cpp
  zasulsky.egor/common/parser.hpp
Labels: .ok, 3/5

#164 hohlova.polina/S5
  hohlova.polina/S5/BinaryTreeII.cpp
  hohlova.polina/S5/BinaryTreeII.hpp
  hohlova.polina/S5/keySumm.hpp
  hohlova.polina/S5/main.cpp
  hohlova.polina/common/BinarySearchTree.hpp
Labels: .ok, 3/5
