Repository yzharko/spbspu-labs-2024-aads, pull requests merged in 2024-04, with the labels that each got.

#41 khoroshkin.maksim/S1
  khoroshkin.maksim/S1/funcs.hpp
  khoroshkin.maksim/S1/list.hpp
  khoroshkin.maksim/S1/main.cpp
Labels: 5/5, .chosenOne

#44 redko.arina/S1
  redko.arina/S1/inputFunctions.cpp
  redko.arina/S1/inputFunctions.hpp
  redko.arina/S1/list.hpp
  redko.arina/S1/main.cpp
  redko.arina/S1/outputFunctions.cpp
  redko.arina/S1/outputFunctions.hpp
Labels: .ok, 5/5, .chosenOne

#75 zasulsky.egor/S0
  zasulsky.egor/S0/main.cpp
Labels: .ok

#46 psarev.alexandr/S1
  psarev.alexandr/S1/divideFuncs.cpp
  psarev.alexandr/S1/divideFuncs.hpp
  psarev.alexandr/S1/ioFuncs.hpp
  psarev.alexandr/S1/list.hpp
  psarev.alexandr/S1/main.cpp
Labels: .ok, 5/5

#55 sobolevsky.misha/S1
  sobolevsky.misha/S1/iterator.hpp
  sobolevsky.misha/S1/list.hpp
  sobolevsky.misha/S1/main.cpp
  sobolevsky.misha/S1/node.hpp
Labels: .ok, 3/5

#49 nikiforov.alexander/S1
  nikiforov.alexander/S1/functions.hpp
  nikiforov.alexander/S1/list.hpp
  nikiforov.alexander/S1/main.cpp
Labels: .ok, 5/5

#57 sukacheva.maria/S1
  sukacheva.maria/S1/DataProcessing.cpp
  sukacheva.maria/S1/DataProcessing.hpp
  sukacheva.maria/S1/List.hpp
  sukacheva.maria/S1/Node.hpp
  sukacheva.maria/S1/main.cpp
Labels: .ok, 4/5, .chosenOne

#74 redko.arina/S2
  redko.arina/S2/expressionTypes.cpp
  redko.arina/S2/expressionTypes.hpp
  redko.arina/S2/main.cpp
  redko.arina/S2/postfix.cpp
  redko.arina/S2/postfix.hpp
  redko.arina/S2/processingFunctions.cpp
  redko.arina/S2/processingFunctions.hpp
  redko.arina/S2/queue.hpp
  redko.arina/S2/stack.hpp
  redko.arina/common/inputFunctions.cpp
  redko.arina/common/inputFunctions.hpp
  redko.arina/common/list.hpp
Labels: .ok, 5/5, .chosenOne

#59 taskaev.matvei/S1
  taskaev.matvei/S1/List.hpp
  taskaev.matvei/S1/functionList.hpp
  taskaev.matvei/S1/main.cpp
Labels: .ok, 4/5

#54 doroshenko.anna/S1
  doroshenko.anna/S1/functions.hpp
  doroshenko.anna/S1/list.hpp
  doroshenko.anna/S1/main.cpp
Labels: .ok, 4/5

#51 Kaseev.andrey/s1
  kaseev.andrey/S1/AdditionalFunctions.cpp
  kaseev.andrey/S1/AdditionalFunctions.hpp
  kaseev.andrey/S1/MaineArray.hpp
  kaseev.andrey/S1/main.cpp
Labels: .ok, 4/5

#43 Anikanov.vladislav/S1
  anikanov.vladislav/S1/list.hpp
  anikanov.vladislav/S1/main.cpp
  anikanov.vladislav/S1/mainExtensions.cpp
  anikanov.vladislav/S1/mainExtensions.hpp
Labels: .ok, 5/5

#76 khoroshkin.maksim/S2
  khoroshkin.maksim/S2/functions.cpp
  khoroshkin.maksim/S2/functions.hpp
  khoroshkin.maksim/S2/main.cpp
  khoroshkin.maksim/S2/queue.hpp
  khoroshkin.maksim/S2/stack.hpp
  khoroshkin.maksim/S2/typization.cpp
  khoroshkin.maksim/S2/typization.hpp
  khoroshkin.maksim/common/list.hpp
Labels: .ok, 5/5, .chosenOne

#61 miheev.egor/S1
  miheev.egor/S1/IOProcessing.cpp
  miheev.egor/S1/IOProcessing.hpp
  miheev.egor/S1/list.hpp
  miheev.egor/S1/main.cpp
Labels: .ok, 4/5

#68 kovshikov.nikita/S1
  kovshikov.nikita/S1/IOProcess.cpp
  kovshikov.nikita/S1/IOProcess.hpp
  kovshikov.nikita/S1/doublelist.hpp
  kovshikov.nikita/S1/main.cpp
  kovshikov.nikita/S1/node.hpp
Labels: .ok, 4/5
